### ISSUE TITLE
Coala auto run after reset / power loss

### ISSUE THREAD

**Issue by GrueneNeun** [TUDSSL/Coala#1]
I am trying to use coala within code composer studio. Running it trough the debug option with a simple self made app works well, but after pressing reset or unplugging and replugging the MSP430FR5969 it won't start up again.

Additionally i can't find the line in the Linker Script which is mentioned in the readme to be edited. The one closest matching it is 
"FRAM (rx)        : ORIGIN = 0x4400, LENGTH = 0xBB80 /* END=0xFF7F, size 48000 */"

**Comment by przemyslaw-pawelczak** [comment]
Dear @GrueneNeun - Thanks a lot for posting this issue and glad to see your interest in our project. We will be getting back to you with an answer shortly.

**Comment by amjadmajid** [comment]
Hi @GrueneNeun 
Thanks for your interest and question. 
1. You do not need to build Coala with CCS. You can go to the app folder and type `make` and it will build it. Then, you can flash it to your MCU with a different tool. 
2. Coala requires GCC or Clang. Set your environment in this file https://github.com/TUDSSL/Coala/blob/master/maker/envCom.mk
3. Modifications in the linker file https://github.com/TUDSSL/Coala/blob/c0f9be03ebda4301b217dd991b83065f910fffdb/coala/linkerScripts/8KB_pages/msp430fr5969.ld#L49 and the 2 lines below it.  Also https://github.com/TUDSSL/Coala/blob/c0f9be03ebda4301b217dd991b83065f910fffdb/coala/linkerScripts/8KB_pages/msp430fr5969.ld#L237 and the 18 lines below it. 

<hr>

Using __CCS__ <br>
I have built this app with CCS https://github.com/amjadmajid/CoalaRepo/tree/master/apps/sort. If you want to follow what I have done, please make sure that 

* you direct CCS to use the linker script in this app folder, and
* you link Coala and the needed libraries properly (https://www.youtube.com/watch?v=FzHtq51IjDM).
* For further assistance, we need to know more about the problem (more details). Thank you very much.

**Comment by GrueneNeun** [comment]
Sorry for responding so late.
Using the Youtube Video and your hint about the linker script i have been successfully able to get a Coala up and running inside a CCS Project.
Thank you very much for your help.
