### ISSUE TITLE
Miss alpaca-gcc lib to compile apps

### ISSUE THREAD

**Issue by bernabeu-a** [TUDSSL/Coala#3]
When compiling an app, it seems that alpaca-gcc directory is missing in libs directory

**Comment by przemyslaw-pawelczak** [comment]
Dear @bernabeu-a thanks for this issue. I believe the `alpaca-gcc` should be found here https://github.com/amjadmajid/intermittent_backscatter/tree/master/coala-repo/libs/alpaca-gcc

@amjadmajid can you confirm this is the right repo? If yes - @bernabeu-a please make the necessary correction and do pull request. Let us know if you have any other question.
